/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basicLibrary;
import java.util.*;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }


    public static int[] roll(int rolls) {
        Random rnd = new Random();
        int[] numsRolled = new int[rolls];
        System.out.println(numsRolled + " Arr");
        for (int i = 0; i < numsRolled.length; i++) {
            numsRolled[i] = rnd.nextInt((6 - 1) + 1) + 1;
            System.out.println(i);
        }

        return numsRolled;
    }

    public static boolean containsDuplicates(int[] arr){
        System.out.println(Arrays.toString(arr));
        for(int i=0; i<arr.length; i++){
            for(int j=i+1; j<arr.length; j++){
                if(arr[i]==arr[j]){
                    return true;

                }
            }
        }
        return false;
    }

//    public static
//    public static

    public static String hashyMappy(){
        int high =0;
        int low =200;
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };

        HashSet<Integer> monthTemps = new HashSet<>();

        for (int i =0; i<weeklyMonthTemperatures.length; i++){
            for (int j=0; j<weeklyMonthTemperatures[i].length; j++){
                monthTemps.add(weeklyMonthTemperatures[i][j]);
                 if( weeklyMonthTemperatures[i][j]>high){
                     high=weeklyMonthTemperatures[i][j];
                 }else if (weeklyMonthTemperatures[i][j]<low){
                     low=weeklyMonthTemperatures[i][j];
                 }
            }
        }
        String tempNotSeen="";
        for(int i=low; i<=high; i++){
            if(!monthTemps.contains(i))
                tempNotSeen += String.format("Never saw temperature: %d",i);
        }
        return tempNotSeen;
    }

    public static String tally(){
        List<String> votes = new ArrayList<>();
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Shrub");
        votes.add("Hedge");
        votes.add("Shrub");
        votes.add("Bush");
        votes.add("Hedge");
        votes.add("Bush");

        HashMap<String,Integer> plantVoteNumbers = new HashMap<>();
        for(String plant: votes){
            plantVoteNumbers.put(plant, 0);
        }

        



    }



}
